version: '3'
services:
homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
    - /${PATH_CONFIG}:/config
    environment:
    - TZ=Europe/Berlin
    restart: always
    network_mode: host
